controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy = -250
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.over(false)
})
let projectile: Sprite = null
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ccccc.........
    ........cc11111c........
    .......cb111111bc.......
    ......cbd1111111c.......
    ......cddd111111dc......
    ......cdddd11111dc......
    ......cddddddd11dc......
    ......cddddddd111c......
    ......cddddddc211c......
    .......cbdddb1111bc.....
    ........cccccdb1b1c.....
    .......ccccccccbcbc.....
    ....cc.ccccccccccc......
    .....cccccccc...........
    .....ccccccb1b1c........
    ......ccccccbcbc........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
mySprite.setPosition(20, 70)
mySprite.ay = 500
tiles.setTilemap(tilemap`level1`)
scene.setBackgroundColor(13)
let speed = -80
game.onUpdate(function () {
    if (info.score() <= 10) {
        speed += -0.5
    }
})
game.onUpdateInterval(1500, function () {
    projectile = sprites.createProjectileFromSide(img`
        1 e e e e e e 1 
        e e e e e e e e 
        1 1 1 1 1 1 1 1 
        e e e e e e e e 
        e e e e e e e e 
        1 1 1 1 1 1 1 1 
        e e e e e e e e 
        1 e e e e e e 1 
        `, speed, 0)
    info.changeScoreBy(1)
    tiles.placeOnTile(projectile, tiles.getTileLocation(9, 5))
})
